version: '3.2'

services:
  api:
    container_name: api
    build: ../server
    hostname: api
    depends_on:
      - mysql
      - redis
    ports:
      - '3000:3000'
    volumes:
      - ../server:/usr/src/service/server
    working_dir: /usr/src/service/server
    command: 'yarn start'
    networks:
      - elk
  
  adminer:
    container_name: adminer
    image: adminer:latest
    ports:
      - "8080:8080"
    networks:
      - elk

  redis:
    image: redis
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - ../docker/redis/data:/data
      - ../docker/redis/redis.conf:/usr/local/etc/redis/redis.conf
    command:
      - redis-server
      - /usr/local/etc/redis/redis.conf
    networks:
      - elk

  mysql:
    image: mysql:8.0
    hostname: mysql
    container_name: mysql
    ports:
      - '3306:3306'
    volumes:
      - ../docker/mysql-data:/var/lib/mysql
      - ../docker/mysql-config:/etc/mysql/conf.d
    command: --default-authentication-plugin=mysql_native_password --port=3306
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: database
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      USER: 1000
    networks:
        - elk

networks:
  elk:
    driver: bridge

volumes:
  elasticsearch:
